### ISSUE TITLE
Why is this not on PyPi?

### ISSUE THREAD

**Issue by ughstudios** [CommunityDragon/CDTB#64]
Any ideas? It's super easy to setup, can be done in a day.

**Comment by benoitryder** [comment]
As said in #63, we never thought about it before... and had vacations, work, since then.

Just making a quick package should work but it may not be the good way to do it. Along with the source code itself (and that doesn't change very often) we have the hash files (large data files). Those files are/should be updated on a regular basis.
(Note that those files are large but compress very well so we shouldn't hit the pypi upload limit.)

Ideally, those files would be on a separate repository; it has already been considered but never actually done, and might affect the workflow of people that are already using this repository (sometimes only for the hashes).
This would also be much less convenient for Pypi package, as it would require users to fetch/update data (and add code to do it easily).

**Comment by benoitryder** [comment]
Done!
https://pypi.org/project/cdtb/
